# Generated by Django 6.0.1 on 2026-01-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_tmdb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='poster_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='runtime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
