# Generated by Django 6.0.1 on 2026-01-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_is_tmdb_review_poster_path_review_tmdb_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='best_scene_image',
            field=models.ImageField(blank=True, null=True, upload_to='best_scenes/'),
        ),
        migrations.AddField(
            model_name='review',
            name='tmdb_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='review',
            name='cast',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='director',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
