# Generated by Django 6.0.1 on 2026-01-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_review_best_scene_image_review_tmdb_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='review',
            name='tmdb_rating',
        ),
        migrations.AlterField(
            model_name='review',
            name='cast',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='review',
            name='director',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='review',
            name='genres',
            field=models.ManyToManyField(related_name='reviews', to='reviews.genre'),
        ),
    ]
