# Generated by Django 6.0 on 2026-01-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_alter_idea_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='devtool',
        ),
        migrations.AddField(
            model_name='idea',
            name='devtools',
            field=models.ManyToManyField(blank=True, to='ideas.devtool'),
        ),
    ]
