# Generated by Django 5.2.4 on 2026-01-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='calories',
            field=models.FloatField(default=0.0, verbose_name='칼로리(Kcal)'),
        ),
        migrations.AddField(
            model_name='post',
            name='carbs',
            field=models.FloatField(default=0.0, verbose_name='탄수화물(g)'),
        ),
        migrations.AddField(
            model_name='post',
            name='fat',
            field=models.FloatField(default=0.0, verbose_name='지방(g)'),
        ),
        migrations.AddField(
            model_name='post',
            name='protein',
            field=models.FloatField(default=0.0, verbose_name='단백질(g)'),
        ),
    ]
