# Generated by Django 5.2.4 on 2026-01-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_calories_post_carbs_post_fat_post_protein'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='nutrition_image',
            field=models.ImageField(blank=True, upload_to='nutrition/%Y%m%d', verbose_name='영양성분 이미지'),
        ),
    ]
