# Generated by Django 5.2.4 on 2026-01-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_nutrition_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.CharField(blank=True, max_length=200, verbose_name='해시태그'),
        ),
    ]
