# Generated by Django 6.0.1 on 2026-01-22 08:51

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_image_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='photo',
            field=models.ImageField(upload_to=posts.models.uuid_name_upload_to),
        ),
    ]
