# Generated by Django 6.0.1 on 2026-01-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_postimage_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='image',
            field=models.ImageField(default='', upload_to='stories/'),
            preserve_default=False,
        ),
    ]
